SELECT * FROM VISITOR_TB;

SELECT COUNT(*) FROM VISITOR_TB WHERE VST_TIME BETWEEN '2017-05-01' AND '2020-01-31';
SELECT IP_ADDRESS, COUNT(*) FROM VISITOR_TB GROUP BY IP_ADDRESS HAVING COUNT(*) >= 2;
SELECT DATE_FORMAT(VST_TIME, '%Y'), COUNT(*) FROM VISITOR_TB GROUP BY DATE_FORMAT(VST_TIME, '%Y');
SELECT DATE_FORMAT(VST_TIME, '%m'), COUNT(*) FROM VISITOR_TB GROUP BY DATE_FORMAT(VST_TIME, '%m') ORDER BY COUNT(*) DESC;
SELECT DATE_FORMAT(VST_TIME, '%Y-%m') AS 방문월, CASE WHEN VST_PATH=1 THEN '검색' WHEN VST_PATH=2 THEN '부산교통공사' END AS 방문경로, COUNT(*) AS 방문자수
	FROM VISITOR_TB GROUP BY DATE_FORMAT(VST_TIME, '%Y-%m'), VST_PATH 
    ORDER BY DATE_FORMAT(VST_TIME, '%Y-%m'), VST_PATH ASC;